services:
  ifcopenshell:
    platform: linux/amd64
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./:/usr/src/app
    command: python3 main.py --file-a test1.ifc --file-b test2.ifc --selector-b IfcWall --mode intersection --tolerance 0.01 --check-all True
