services:
  ifcopenshell:
    platform: linux/amd64
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./:/usr/src/app
    command: python3 main.py --file-a data/golden.ifc --file-b data/test1.ifc --selector-b IfcWall --mode intersection --tolerance 0.01 --check-all True
