services:
  ifcopenshell:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./:/usr/src/app
    command: python3 main.py --ifc-path data/ifc/test1.ifc --output outputs/file.obj
